<?php

namespace Lyrica\EirinBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppearanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppearanceRepository extends EntityRepository
{
}