appearance_show:
    pattern: /show/{id}
    defaults:
        _controller: LyricaEirinBundle:Appearance:show
    requirements:
        id: \d+

appearance_add_role:
    pattern: /{app_id}/add/role
    defaults:
        _controller: LyricaEirinBundle:Appearance:addRole
    requirements:
        id: \d+